Added ssl support to mongodb kamelets.
apache/camel-kamelets pull request #1251
Opened 2023-01-23 16:26 UTC by valdar

2023-01-23 16:28 UTC, oscerd requested changes

2023-01-23 16:28 UTC, oscerd commented on kamelets/mongodb-changes-stream-source.kamelet.yaml
> +        type: "#class:org.bf2.cos.connector.camel.mongodb.SslAwareMongoClient"
Can you change the package name?

2023-01-24 11:37 UTC, valdar commented on kamelets/mongodb-changes-stream-source.kamelet.yaml
> +        type: "#class:org.bf2.cos.connector.camel.mongodb.SslAwareMongoClient"
done

2023-01-24 11:41 UTC, oscerd approved these changes

2023-01-25 07:00 UTC, merged